
[build-system]
# see https://github.com/cvxgrp/cvxpy/issues/968 for numpy version
requires = ["setuptools>=61", "wheel", "setuptools_scm>=6.2", "cython", "numpy>=1.16.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "pygsti/_version.py"